package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClassName(java.lang.String className) {
		set("className", className);
		return (M)this;
	}
	
	public java.lang.String getClassName() {
		return getStr("className");
	}

	public M setClassNo(java.lang.Integer classNo) {
		set("classNo", classNo);
		return (M)this;
	}
	
	public java.lang.Integer getClassNo() {
		return getInt("classNo");
	}

	public M setMajorId(java.lang.Integer majorId) {
		set("majorId", majorId);
		return (M)this;
	}
	
	public java.lang.Integer getMajorId() {
		return getInt("majorId");
	}

	public M setGradeId(java.lang.Integer gradeId) {
		set("gradeId", gradeId);
		return (M)this;
	}
	
	public java.lang.Integer getGradeId() {
		return getInt("gradeId");
	}

}
