package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserWork<M extends BaseUserWork<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkTime(java.util.Date WorkTime) {
		set("WorkTime", WorkTime);
		return (M)this;
	}
	
	public java.util.Date getWorkTime() {
		return get("WorkTime");
	}

	public M setWorkPlace(java.lang.String WorkPlace) {
		set("WorkPlace", WorkPlace);
		return (M)this;
	}
	
	public java.lang.String getWorkPlace() {
		return getStr("WorkPlace");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setReviewAt(java.util.Date reviewAt) {
		set("reviewAt", reviewAt);
		return (M)this;
	}
	
	public java.util.Date getReviewAt() {
		return get("reviewAt");
	}

	public M setImagePath(java.lang.String imagePath) {
		set("imagePath", imagePath);
		return (M)this;
	}
	
	public java.lang.String getImagePath() {
		return getStr("imagePath");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setWorkId(java.lang.Integer workId) {
		set("workId", workId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkId() {
		return getInt("workId");
	}

	public M setReviewId(java.lang.Integer reviewId) {
		set("reviewId", reviewId);
		return (M)this;
	}
	
	public java.lang.Integer getReviewId() {
		return getInt("reviewId");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public M setScoreType(java.lang.Integer scoreType) {
		set("scoreType", scoreType);
		return (M)this;
	}
	
	public java.lang.Integer getScoreType() {
		return getInt("scoreType");
	}

}
