package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReview<M extends BaseReview<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setReviewName(java.lang.String reviewName) {
		set("reviewName", reviewName);
		return (M)this;
	}
	
	public java.lang.String getReviewName() {
		return getStr("reviewName");
	}

}
