package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideo<M extends BaseVideo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVideoName(java.lang.String VideoName) {
		set("VideoName", VideoName);
		return (M)this;
	}
	
	public java.lang.String getVideoName() {
		return getStr("VideoName");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public M setSubjectId(java.lang.Integer SubjectId) {
		set("SubjectId", SubjectId);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("SubjectId");
	}

	public M setUploadTime(java.util.Date UploadTime) {
		set("UploadTime", UploadTime);
		return (M)this;
	}
	
	public java.util.Date getUploadTime() {
		return get("UploadTime");
	}

}
