package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacherLinkStudent<M extends BaseTeacherLinkStudent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setClassId(java.lang.Integer classId) {
		set("classId", classId);
		return (M)this;
	}
	
	public java.lang.Integer getClassId() {
		return getInt("classId");
	}

	public M setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
		return (M)this;
	}
	
	public java.lang.String getTeacherId() {
		return getStr("teacherId");
	}

}
