package com.cxxy.oem.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWork<M extends BaseWork<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkName(java.lang.String WorkName) {
		set("WorkName", WorkName);
		return (M)this;
	}
	
	public java.lang.String getWorkName() {
		return getStr("WorkName");
	}

	public M setWorkContent(java.lang.String WorkContent) {
		set("WorkContent", WorkContent);
		return (M)this;
	}
	
	public java.lang.String getWorkContent() {
		return getStr("WorkContent");
	}

	public M setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
		return (M)this;
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public M setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
		return (M)this;
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

	public M setDeadLine(java.util.Date DeadLine) {
		set("DeadLine", DeadLine);
		return (M)this;
	}
	
	public java.util.Date getDeadLine() {
		return get("DeadLine");
	}

	public M setSubjectId(java.lang.Integer SubjectId) {
		set("SubjectId", SubjectId);
		return (M)this;
	}
	
	public java.lang.Integer getSubjectId() {
		return getInt("SubjectId");
	}

}
