package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseGender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gender extends BaseGender<Gender> {
	public static final Gender dao = new Gender().dao();
}
