package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseMajor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Major extends BaseMajor<Major> {
	public static final Major dao = new Major().dao();
}
