package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Review extends BaseReview<Review> {
	public static final Review dao = new Review().dao();
}
