package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Score extends BaseScore<Score> {
	public static final Score dao = new Score().dao();
}
