package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Source extends BaseSource<Source> {
	public static final Source dao = new Source().dao();
}
