package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subject extends BaseSubject<Subject> {
	public static final Subject dao = new Subject().dao();
}
