package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseSysUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUrl extends BaseSysUrl<SysUrl> {
	public static final SysUrl dao = new SysUrl().dao();
}
