package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseTeacherLinkStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeacherLinkStudent extends BaseTeacherLinkStudent<TeacherLinkStudent> {
	public static final TeacherLinkStudent dao = new TeacherLinkStudent().dao();
}
