package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseUserWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserWork extends BaseUserWork<UserWork> {
	public static final UserWork dao = new UserWork().dao();
}
