package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseVideoSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoSign extends BaseVideoSign<VideoSign> {
	public static final VideoSign dao = new VideoSign().dao();
}
