package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {
	public static final Video dao = new Video().dao();
}
