package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Work extends BaseWork<Work> {
	public static final Work dao = new Work().dao();
}
